/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutOctobotsRouteImport } from './routes/_layout/octobots'
import { Route as LayoutOctobotsNewRouteImport } from './routes/_layout/octobots/new'
import { Route as LayoutOctobotsImportRouteImport } from './routes/_layout/octobots/import'
import { Route as LayoutOctobotsStrategiesRouteImport } from './routes/_layout/octobots/new/strategies'
import { Route as LayoutAccountsRouteImport } from './routes/_layout/accounts'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutTentaclesIndexRouteImport } from './routes/_layout/tentacles/index'
import { Route as LayoutTentaclesNewRouteImport } from './routes/_layout/tentacles/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOctobotsRoute = LayoutOctobotsRouteImport.update({
  id: '/octobots',
  path: '/octobots',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOctobotsNewRoute = LayoutOctobotsNewRouteImport.update({
  id: '/octobots/new',
  path: '/octobots/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOctobotsImportRoute = LayoutOctobotsImportRouteImport.update({
  id: '/octobots/import',
  path: '/octobots/import',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOctobotsStrategiesRoute = LayoutOctobotsStrategiesRouteImport.update({
  id: '/octobots/new/strategies',
  path: '/octobots/new/strategies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountsRoute = LayoutAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTentaclesIndexRoute = LayoutTentaclesIndexRouteImport.update({
  id: '/tentacles',
  path: '/tentacles',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTentaclesNewRoute = LayoutTentaclesNewRouteImport.update({
  id: '/tentacles/new',
  path: '/tentacles/new',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/octobots': typeof LayoutOctobotsRoute
  '/octobots/new': typeof LayoutOctobotsNewRoute
  '/octobots/import': typeof LayoutOctobotsImportRoute
  '/octobots/new/strategies': typeof LayoutOctobotsStrategiesRoute
  '/accounts': typeof LayoutAccountsRoute
  '/settings': typeof LayoutSettingsRoute
  '/tentacles': typeof LayoutTentaclesIndexRoute
  '/tentacles/new': typeof LayoutTentaclesNewRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/octobots': typeof LayoutOctobotsRoute
  '/octobots/new': typeof LayoutOctobotsNewRoute
  '/octobots/import': typeof LayoutOctobotsImportRoute
  '/octobots/new/strategies': typeof LayoutOctobotsStrategiesRoute
  '/accounts': typeof LayoutAccountsRoute
  '/settings': typeof LayoutSettingsRoute
  '/tentacles': typeof LayoutTentaclesIndexRoute
  '/tentacles/new': typeof LayoutTentaclesNewRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/octobots': typeof LayoutOctobotsRoute
  '/_layout/octobots/new': typeof LayoutOctobotsNewRoute
  '/_layout/octobots/import': typeof LayoutOctobotsImportRoute
  '/_layout/octobots/new/strategies': typeof LayoutOctobotsStrategiesRoute
  '/_layout/accounts': typeof LayoutAccountsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tentacles': typeof LayoutTentaclesIndexRoute
  '/_layout/tentacles/new': typeof LayoutTentaclesNewRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/octobots'
    | '/octobots/new'
    | '/octobots/import'
    | '/octobots/new/strategies'
    | '/accounts'
    | '/settings'
    | '/tentacles'
    | '/tentacles/new'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/octobots'
    | '/octobots/new'
    | '/octobots/import'
    | '/octobots/new/strategies'
    | '/accounts'
    | '/settings'
    | '/tentacles'
    | '/tentacles/new'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/octobots'
    | '/_layout/octobots/new'
    | '/_layout/octobots/import'
    | '/_layout/octobots/new/strategies'
    | '/_layout/accounts'
    | '/_layout/settings'
    | '/_layout/tentacles'
    | '/_layout/tentacles/new'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/octobots': {
      id: '/_layout/octobots'
      path: '/octobots'
      fullPath: '/octobots'
      preLoaderRoute: typeof LayoutOctobotsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/octobots/new': {
      id: '/_layout/octobots/new'
      path: '/octobots/new'
      fullPath: '/octobots/new'
      preLoaderRoute: typeof LayoutOctobotsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/octobots/import': {
      id: '/_layout/octobots/import'
      path: '/octobots/import'
      fullPath: '/octobots/import'
      preLoaderRoute: typeof LayoutOctobotsImportRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/octobots/new/strategies': {
      id: '/_layout/octobots/new/strategies'
      path: '/octobots/new/strategies'
      fullPath: '/octobots/new/strategies'
      preLoaderRoute: typeof LayoutOctobotsStrategiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/accounts': {
      id: '/_layout/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof LayoutAccountsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tentacles': {
      id: '/_layout/tentacles'
      path: '/tentacles'
      fullPath: '/tentacles'
      preLoaderRoute: typeof LayoutTentaclesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tentacles/new': {
      id: '/_layout/tentacles/new'
      path: '/tentacles/new'
      fullPath: '/tentacles/new'
      preLoaderRoute: typeof LayoutTentaclesNewRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutOctobotsRoute: typeof LayoutOctobotsRoute
  LayoutOctobotsNewRoute: typeof LayoutOctobotsNewRoute
  LayoutOctobotsImportRoute: typeof LayoutOctobotsImportRoute
  LayoutOctobotsStrategiesRoute: typeof LayoutOctobotsStrategiesRoute
  LayoutAccountsRoute: typeof LayoutAccountsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTentaclesIndexRoute: typeof LayoutTentaclesIndexRoute
  LayoutTentaclesNewRoute: typeof LayoutTentaclesNewRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutOctobotsRoute: LayoutOctobotsRoute,
  LayoutOctobotsNewRoute: LayoutOctobotsNewRoute,
  LayoutOctobotsImportRoute: LayoutOctobotsImportRoute,
  LayoutOctobotsStrategiesRoute: LayoutOctobotsStrategiesRoute,
  LayoutAccountsRoute: LayoutAccountsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTentaclesIndexRoute: LayoutTentaclesIndexRoute,
  LayoutTentaclesNewRoute: LayoutTentaclesNewRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
